# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [17]:
import numpy as np
npary=np.random.randint(10, 25,25)
print(npary)

[16 18 24 13 11 10 12 16 15 14 19 11 24 14 17 21 18 12 20 15 11 18 11 10
 20]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
npary1=np.arange(1,50,2)

print("Length of Array is: ",len(npary1))


Length of Array is:  25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
npary2=np.linspace(4,7,27)
print(npary2)

[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
x = np.random.random((5,4))
print("the matrix is :",x)
round_matrix=np.round(x, 2)
print("******************************************************")
print("the rounded matrix is: ",round_matrix)

the matrix is : [[0.93823026 0.57437963 0.35184633 0.41089162]
 [0.07552487 0.9539662  0.75367265 0.29932607]
 [0.6856748  0.20973973 0.92192529 0.40545293]
 [0.7317737  0.03630071 0.14543632 0.15714033]
 [0.65626564 0.21789447 0.72947498 0.38389179]]
******************************************************
the rounded matrix is:  [[0.94 0.57 0.35 0.41]
 [0.08 0.95 0.75 0.3 ]
 [0.69 0.21 0.92 0.41]
 [0.73 0.04 0.15 0.16]
 [0.66 0.22 0.73 0.38]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
m=np.random.randint(5,15,(5,5))
m

array([[ 9, 14, 12,  8, 14],
       [10, 10, 12,  9,  8],
       [ 6,  6, 10, 14,  9],
       [10, 12,  6, 14,  6],
       [12, 10,  5,  8, 12]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
zero=np.zeros(19,dtype=int)
print(zero)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
one=np.ones([3,3])
print(np.float32(one))




[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [8]:
x = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(x)
y=x.flatten()
mid_value=y[int(len(y)/2)]
print("The center pixel of the given matrix is ",mid_value)
type(y)


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
The center pixel of the given matrix is  3


numpy.ndarray

#### 10. Print the all the elements of 3rd row of the matrix

In [9]:
third_row=x[int(len(x)/2)]
print(third_row)

[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [10]:
col_4=[row[3] for row in x]
print(col_4)



[34, 65, 76, 54, 5]


#### 12. Print the 4 corner pixels of the matrix

In [11]:
n = len(x) #len of rows
m = len(x[0]) # length of column
corner=[x[0][0],x[0][m - 1],x[n - 1][0],x[n - 1][m - 1]]
print(corner)



[9, 45, 23, 8]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [12]:
m1 = x[:2, 2:4]
print("Matrix 1 :",m1)
m2 = x[3:, :2]
print("Matrix 2 :",m2)
m3 = x[2:, 2:]
print("Matrix 3 :",m3)

Matrix 1 : [[50 34]
 [34 65]]
Matrix 2 : [[ 7  8]
 [23 12]]
Matrix 3 : [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [13]:
reshaped_m1=m1.flatten()
print("Reshaped M1: ",reshaped_m1)
reshaped_m2=m2.flatten()
print("Reshaped M2: ",reshaped_m2)
reshaped_m3=m3.flatten()
print("Reshaped M3: ",reshaped_m3)






Reshaped M1:  [50 34 34 65]
Reshaped M2:  [ 7  8 23 12]
Reshaped M3:  [ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [14]:
vertical_matrix=np.vstack((m1,m2))
print(vertical_matrix)
horizontal_matrix=np.hstack((m1,m2))
print("******************************************************")
print(horizontal_matrix)




[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
******************************************************
[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [15]:
add=m1+m2
sub=m1-m2
multiply=m1*m2
divide=m1/m2
print("Addition of matrix : ",add)
print("Subraction of matrix : ",sub)
print("multiplication of matrix : ",multiply)
print("division of matrix : ",divide)



Addition of matrix :  [[57 42]
 [57 77]]
Subraction of matrix :  [[43 26]
 [11 53]]
multiplication of matrix :  [[350 272]
 [782 780]]
division of matrix :  [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [16]:
rmd_m3=m3[1:, :2]
sum_of_matrix=rmd_m3+m1
print("Addition of matrix : ",sum_of_matrix)




Addition of matrix :  [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [17]:
mean_m1=np.average(m1, axis=0)
m4=np.vstack((m1,mean_m1))
print(m4)




[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [18]:
matrix_multiplication=np.matmul(m3, m4)
print("matrix multiplication between m3 and m4 : ",matrix_multiplication)




matrix multiplication between m3 and m4 :  [[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [33]:
row_means = x.mean(axis=1)
row_variance = x.var(axis=1)
row_std = x.std(axis=1)
print("the mean is : ",row_means)
print("the maximum mean is :",max(row_means))
print("the minimum mean is : ",min(row_means))
print("the variance is : ",row_variance)
print("the maximum variance is :",max(row_variance))
print("the minimum variance is : ",min(row_variance))
print("the standard deviation is : ",row_std)
print("the maximum standard deviation is :",max(row_std))
print("the minimum standard deviation is : ",min(row_std))

the mean is :  [32.6 27.6 18.8 16.2 11.2]
the maximum mean is : 32.6
the minimum mean is :  11.2
the variance is :  [214.64 548.24 820.16 357.76  39.76]
the maximum variance is : 820.1600000000001
the minimum variance is :  39.760000000000005
the standard deviation is :  [14.65059726 23.41452541 28.63843571 18.91454467  6.30555311]
the maximum standard deviation is : 28.63843571147
the minimum standard deviation is :  6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [73]:
runs_scored=np.array([['msd',54,60,10,65],['kholi',102,2,78,32],['rohit',3,110,1,92],['rahul',56,6,12,42],['dhawan',12,8,22,11]])
balls_faced=np.array([['msd',50,42,22,78],['kholi',95,8,65,43],['rohit',9,100,7,101],['rahul',27,3,11,31],['dhawan',24,20,36,27]])
runs=runs_scored[:,1:]
balls=balls_faced[:,1:]
runs=runs.astype(int)
balls=balls.astype(int)
cccc=(runs/balls)*100
print(strike_rate)
avg=runs/4
print(avg)
sortedsr=np.sort(avg)[::-1]
sortedsr


[[108.         142.85714286  45.45454545  83.33333333]
 [107.36842105  25.         120.          74.41860465]
 [ 33.33333333 110.          14.28571429  91.08910891]
 [207.40740741 200.         109.09090909 135.48387097]
 [ 50.          40.          61.11111111  40.74074074]]
[[13.5  15.    2.5  16.25]
 [25.5   0.5  19.5   8.  ]
 [ 0.75 27.5   0.25 23.  ]
 [14.    1.5   3.   10.5 ]
 [ 3.    2.    5.5   2.75]]


array([[ 2.  ,  2.75,  3.  ,  5.5 ],
       [ 1.5 ,  3.  , 10.5 , 14.  ],
       [ 0.25,  0.75, 23.  , 27.5 ],
       [ 0.5 ,  8.  , 19.5 , 25.5 ],
       [ 2.5 , 13.5 , 15.  , 16.25]])

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [138]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
pass_stdnt=marks[marks>50]
fail_stdnt=marks[marks<50]
print("total number of student is: ",len(marks))
print("the number of pass student is: ",len(pass_stdnt))
print("the number of fail student is: ",len(fail_stdnt))
print("total number of student is: ",len(marks))

total number of student is:  10
the number of pass student is:  7
the number of fail student is:  3
total number of student is:  10


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [143]:
ind=np.where((marks > 45) & (marks < 49))
marks[ind]=marks[ind]+5
ind1=np.where((marks >80))
marks[ind1]=marks[ind1]+5
ind2=np.where((marks>100))
marks[ind2]=100
print(marks)

Wall time: 0 ns
Wall time: 0 ns
[ 65  99  52  56 100 100  53  77  80  39]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [32]:
import time
def lst():
    x=list(range(1,60000))
    y=list(range(1,60000))
    res=[]
    for i in range(len(x)):
        res.append((((x[i]**2)+8)/y[i]))
    #print(res)
def npy():
    x=np.array(range(1,60000))
    y=np.array(range(1,60000))
    res=((x**2)+8)/y
    #print(res)
start = time.time()
%time lst()
end = time.time()
print("The time taken for list is :", end-start)
start1 = time.time()
%time npy()
end1 = time.time()
print("The time taken for numpy is :", end1-start1)  





Wall time: 55 ms
The time taken for list is : 0.05601906776428223
Wall time: 15.6 ms
The time taken for numpy is : 0.01562952995300293


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [21]:

res

array([ 9.00000000e+00,  6.00000000e+00,  5.66666667e+00, ...,
       -1.15893675e+04, -1.15871743e+04, -1.15849812e+04])